### ISSUE TITLE
Stamina doesn't regenerate after sprinting to failure.

### ISSUE THREAD

**Issue by Skulldoor** [BVenturaDev/Ealond#15]
Stamina does not seem to recover if stamina is brought to 0 from sprinting. Other stamina-draining behaviors do not seem to stop stamina regen.

Other stamina drain methods tested to 0:
Jumping
Blocking (with shield)
Shield slamming
Swinging melee weapons (maces / swords, both 1 and 2 handed)
Aiming arrows

**Comment by seanmenzies** [comment]
It does now!
