### ISSUE TITLE
Hotbar equipping / swapping has a number of odd behaviors.

### ISSUE THREAD

**Issue by Skulldoor** [BVenturaDev/Ealond#16]
Tools cannot be equipped from the number 4 slot on the hotbar. The message for the item being equipped appears in the lower right, but the animation to equip the item doesn't occur and the tool does not appear in hand.

Tools in the 4 slot can only be equipped by equipping another tool (from another slot on the hotbar) and hitting 4, but rather than the character putting away the previous tool and equipping the tool in the 4 slot, the currently in-hand tool simply turns into whatever is in the 4 slot.

Example: 
Slot 4 is pickaxe. Slot 5 is hammer. Pressing 4 gives 'Equipped Item: Simple Pickaxe', but otherwise nothing happens. Press 5, animation plays, hammer equipped. Press 4, receive equipping message, hammer instantly becomes pickaxe, Pickaxe is now usable.

When trying to swap tools using the hotbar, rather than swapping, the item in hand turns into the requested item, then the requested item is put away.

Example: 
Slot 1 is pickaxe, slot 2 is axe. Press 1, pickaxe is equipped. Press 2, pickaxe model is immediately replaced with axe model as 'unequip' animation is played resulting in nothing in hand. Axe is not equipped until pressing 2 again.

When a weapon is in the number 4 slot, the rules become even more complicated because it seems to have a distinct way of behaving when swapping between one and two handed weapons as well as also frequently equipping the last used tool. Specific explanation of the 'rules' might be exceptionally difficult, but if you think it would help to suss out the problem, I'll do my best to figure out all the weapon swapping rules around the number 4 hotbar slot.

When trying a similar workaround as for tools (equipping a weapon in another slot and then pressing 4), the first equipped weapon turns into the weapon in the number 4 slot, and then the weapon is immediately put away and the character re-equips the last held tool. 

Notable: On a fresh game launch, all weapons and the shield work fine. Behavior in the number 4 slot only becomes odd after equipping a tool for the first time that play session.

**Comment by seanmenzies** [comment]
I think all of these have been resolved in the latest fix. Closing.
