### ISSUE TITLE
Weapon swapping doesn't change stances.

### ISSUE THREAD

**Issue by Skulldoor** [BVenturaDev/Ealond#17]
Swapping between weapons directly in the hotbar uses the stance of the previously equipped weapon.

Example:
If you equip a 2 handed mace and then use the hotbar to equip a 1 handed weapon, the currently held 2 handed weapon instantly turns into the 1 handed weapon, but still held in the 2 handed grip.

Similarly: If a 1 handed weapon is equipped originally and then a 2 handed weapon is selected, the 1 handed weapon becomes the 2 handed weapon instantly and is held in the 1 hand grip. This also allows you to hold a shield at the same time as a 2 handed weapon.

**Comment by TeamchillingHQ** [comment]
found a weird fix. you have to unequip the weapon before it works for right now. no autounequip rn

**Comment by TeamchillingHQ** [comment]
apparently there is more to this bug. since autounequip doesnt work you get bugged sometimes with the bow and hammer etc sticking out. if autounequip gets added this will probably be fixed i think

**Comment by seanmenzies** [comment]
Fixed in the recent update. Closing.
