### ISSUE TITLE
grondel hitting hovel

### ISSUE THREAD

**Issue by TeamchillingHQ** [BVenturaDev/Ealond#19]
Hi as i build the Hovel an Grondel decided to spawn near it and it hit and it crashed my game

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000008

0x00007ff7c5b51d99 Ealond-Win64-Shipping.exe!UMemoryComponentBase::SelectBuildingTarget() [B:\P4Workspaces\EalondDev\Ealond\Source\Ealond\Components\MemoryComponentBase.cpp:788]
0x00007ff7c5b1811e Ealond-Win64-Shipping.exe!AAIBaseCharacter::MoveBlockedBy() [B:\P4Workspaces\EalondDev\Ealond\Source\Ealond\AI\AIBaseCharacter.cpp:274]
0x00007ff7c788ef6a Ealond-Win64-Shipping.exe!UCharacterMovementComponent::HandleImpact() []
0x00007ff7c7890faf Ealond-Win64-Shipping.exe!UCharacterMovementComponent::MoveAlongFloor() []
0x00007ff7c7896c2b Ealond-Win64-Shipping.exe!UCharacterMovementComponent::PhysWalking() []
0x00007ff7c78a741f Ealond-Win64-Shipping.exe!UCharacterMovementComponent::StartNewPhysics() []
0x00007ff7c7893658 Ealond-Win64-Shipping.exe!UCharacterMovementComponent::PerformMovement() []
0x00007ff7c7884222 Ealond-Win64-Shipping.exe!UCharacterMovementComponent::ControlledCharacterMove() []
0x00007ff7c78a8c36 Ealond-Win64-Shipping.exe!UCharacterMovementComponent::TickComponent() []
0x00007ff7c78877cb Ealond-Win64-Shipping.exe!FActorComponentTickFunction::ExecuteTick() []
0x00007ff7c7fb7067 Ealond-Win64-Shipping.exe!TGraphTask<FTickFunctionTask>::ExecuteTask() []
0x00007ff7c5b876fe Ealond-Win64-Shipping.exe!FNamedTaskThread::ProcessTasksUntilQuit() []
0x00007ff7c5b8a9d6 Ealond-Win64-Shipping.exe!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() []
0x00007ff7c7fcb622 Ealond-Win64-Shipping.exe!FTickTaskSequencer::ReleaseTickGroup() []
0x00007ff7c7fd02b7 Ealond-Win64-Shipping.exe!FTickTaskManager::RunTickGroup() []
0x00007ff7c7b9fa68 Ealond-Win64-Shipping.exe!UWorld::Tick() []
0x00007ff7c7a1383c Ealond-Win64-Shipping.exe!UGameEngine::Tick() []
0x00007ff7c48e9964 Ealond-Win64-Shipping.exe!FEngineLoop::Tick() []
0x00007ff7c48f361c Ealond-Win64-Shipping.exe!GuardedMain() []
0x00007ff7c48f369a Ealond-Win64-Shipping.exe!GuardedMainWrapper() []
0x00007ff7c48f440c Ealond-Win64-Shipping.exe!LaunchWindowsStartup() []
0x00007ff7c48fd1c4 Ealond-Win64-Shipping.exe!WinMain() []
0x00007ff7c89c4772 Ealond-Win64-Shipping.exe!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
0x00007ff901467614 KERNEL32.DLL!UnknownFunction []
0x00007ff9034626a1 ntdll.dll!UnknownFunction []

**Comment by seanmenzies** [comment]
Fixed
