### ISSUE TITLE
Add building components amount

### ISSUE THREAD

**Issue by seanmenzies** [BVenturaDev/Ealond#2]
Now there is some randomness applied to tool damage, it seems that if the number is above 100, it adds 100 for two components, and when <100 of one component is already added, the next swing will only add up to 100 and no more of the next component.

**Comment by BVenturaDev** [comment]
I bet I forgot to check for edge cases.  This needs investigating.

**Comment by seanmenzies** [comment]
Literal edge case

**Comment by seanmenzies** [comment]
Also noticed that when adding resources on swing when player has an insufficient amount of a given resource, then returns with the sufficient quantity and swings, you can add more than needed e.g. 132/100
