### ISSUE TITLE
mace - no damage

### ISSUE THREAD

**Issue by TeamchillingHQ** [BVenturaDev/Ealond#23]
hello gentlemen. maces apparently do not work properly yet. they dont deal any damage nor do they properly hit the enemy yet. is this code written already or is it still being coded right now?

**Comment by seanmenzies** [comment]
We still need to go through all equippable items and fill out stats. Avoid the mace for now and don't expect too much from armor resistance. Leaving open so others can see.

**Comment by seanmenzies** [comment]
Damage stats added
