### ISSUE TITLE
new error code i found

### ISSUE THREAD

**Issue by TeamchillingHQ** [BVenturaDev/Ealond#25]
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000010

0x00007ff78c729856 Ealond-Win64-Shipping.exe!UPlayerDamageComponent::OnHitActor() [B:\P4Workspaces\EalondDev\Ealond\Source\Ealond\Components\PlayerDamageComponent.cpp:249]
0x00007ff78c7446c5 Ealond-Win64-Shipping.exe!UPlayerDamageComponent::WeaponTrace() [B:\P4Workspaces\EalondDev\Ealond\Source\Ealond\Components\PlayerDamageComponent.cpp:141]
0x00007ff78c6eede5 Ealond-Win64-Shipping.exe!UPlayerDamageComponent::execWeaponTrace() [B:\P4Workspaces\EalondDev\Ealond\Intermediate\Build\Win64\UnrealGame\Inc\Ealond\UHT\PlayerDamageComponent.gen.cpp:195]
0x00007ff78c94c119 Ealond-Win64-Shipping.exe!UFunction::Invoke() []
0x00007ff78ca204a3 Ealond-Win64-Shipping.exe!UObject::CallFunction() []
0x00007ff78ca21e3f Ealond-Win64-Shipping.exe!UObject::ProcessContextOpcode() []
0x00007ff78ca22c7e Ealond-Win64-Shipping.exe!ProcessLocalScriptFunction() []
0x00007ff78ca22be5 Ealond-Win64-Shipping.exe!UObject::ProcessInternal() []
0x00007ff78c94c119 Ealond-Win64-Shipping.exe!UFunction::Invoke() []
0x00007ff78ca22a92 Ealond-Win64-Shipping.exe!UObject::ProcessEvent() []
0x00007ff78e33a67f Ealond-Win64-Shipping.exe!UAnimNotifyState::Received_NotifyTick() []
0x00007ff78e3071f6 Ealond-Win64-Shipping.exe!UAnimInstance::TriggerAnimNotifies() []
0x00007ff78e2ee2a2 Ealond-Win64-Shipping.exe!UAnimInstance::DispatchQueuedAnimEvents() []
0x00007ff78e4dddcd Ealond-Win64-Shipping.exe!USkeletalMeshComponent::ConditionallyDispatchQueuedAnimEvents() []
0x00007ff78e4e2ea6 Ealond-Win64-Shipping.exe!USkeletalMeshComponent::FinalizeBoneTransform() []
0x00007ff78e94caf2 Ealond-Win64-Shipping.exe!USkeletalMeshComponent::FinalizeAnimationUpdate() []
0x00007ff78e4ed4d2 Ealond-Win64-Shipping.exe!USkeletalMeshComponent::PostAnimEvaluation() []
0x00007ff78e4dcd28 Ealond-Win64-Shipping.exe!USkeletalMeshComponent::CompleteParallelAnimationEvaluation() []
0x00007ff78e4e2c6a Ealond-Win64-Shipping.exe!TGraphTask<FParallelAnimationCompletionTask>::ExecuteTask() []
0x00007ff78c7676fe Ealond-Win64-Shipping.exe!FNamedTaskThread::ProcessTasksUntilQuit() []
0x00007ff78c76a9d6 Ealond-Win64-Shipping.exe!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() []
0x00007ff78ebab622 Ealond-Win64-Shipping.exe!FTickTaskSequencer::ReleaseTickGroup() []
0x00007ff78ebb02b7 Ealond-Win64-Shipping.exe!FTickTaskManager::RunTickGroup() []
0x00007ff78e77fa68 Ealond-Win64-Shipping.exe!UWorld::Tick() []
0x00007ff78e5f383c Ealond-Win64-Shipping.exe!UGameEngine::Tick() []
0x00007ff78b4c9964 Ealond-Win64-Shipping.exe!FEngineLoop::Tick() []
0x00007ff78b4d361c Ealond-Win64-Shipping.exe!GuardedMain() []
0x00007ff78b4d369a Ealond-Win64-Shipping.exe!GuardedMainWrapper() []
0x00007ff78b4d440c Ealond-Win64-Shipping.exe!LaunchWindowsStartup() []
0x00007ff78b4dd1c4 Ealond-Win64-Shipping.exe!WinMain() []
0x00007ff78f5a4772 Ealond-Win64-Shipping.exe!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
0x00007ff918e17614 KERNEL32.DLL!UnknownFunction []
0x00007ff919b226a1 ntdll.dll!UnknownFunction []

**Comment by TeamchillingHQ** [comment]
so for info i had the monument getting hit once. no other info as i dont know what happened and also its not easy to reproduce

**Comment by seanmenzies** [comment]
Think the recent update solved this one. Closing for now.
