### ISSUE TITLE
Grondel Behavior Tree Breaking when Struck by other Grondel

### ISSUE THREAD

**Issue by BVenturaDev** [BVenturaDev/Ealond#27]
To reproduce let one Grondel strike another.

The Grondel will freeze in place on standing up instead of resuming combat.  Happens 100% of the time.

![image](https://github.com/BVenturaDev/Ealond/assets/82062400/8645af60-1413-4f69-9b5e-d67b00c017da)
![image](https://github.com/BVenturaDev/Ealond/assets/82062400/a0e3d4ff-8fbe-458b-aea0-2471d09140b3)

**Comment by seanmenzies** [comment]
Haven't seen this for a few weeks after a decent amount of testing. Closing.
