### ISSUE TITLE
Character actions while in inventory bug

### ISSUE THREAD

**Issue by And-i1** [BVenturaDev/Ealond#30]
If you press the block button while in your inventory it shows the player blocking with the shield or 2 handed sword on the player preview (If you have the shield or sword equipped). I tried this with the bow since it uses the same button as the block. The player preview played the bow draw animation and the bow aiming crosshair appeared in the middle of the screen.
You can also do the following while in your inventory: Shield bash, jump, walk (without moving), shout, dash, etc
All the actions done while in the inventory occur in the game except for walking.

**Comment by seanmenzies** [comment]
Think I got everything here. Good catch!
