### ISSUE TITLE
Game never loads

### ISSUE THREAD

**Issue by And-i1** [BVenturaDev/Ealond#40]
First time I try to join a game it does nothing. The second time it gets stuck on the loading screen forever. Although it might just be a Linux bug. I haven't been able to get past the loading screen at all since the last update.

Build ID: 11913059
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.1.44-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5500
Memory: 15,4 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: ASUS

https://github.com/BVenturaDev/Ealond/assets/55852971/28330b78-b0e0-4807-8553-e451ca1d08da

**Comment by And-i1** [comment]
I don't know why no one has posted this bug yet unless it's Linux-only so I won't be posting more issues for now.

**Comment by seanmenzies** [comment]
We're trying to reproduce this. Update to follow.

**Comment by seanmenzies** [comment]
This was a really weird bug. Fixed in hotfix 19/08.
